name = 'class_property'
version = '0.0.1'
description = 'Class property that shares the same value with the class and any instance.'
url = 'https://github.com/justengel/class_property'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
